package com.kidsdynamic.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kidsdynamic.data.dao.DB_User;
import com.kidsdynamic.data.dao.DB_Kids;
import com.kidsdynamic.data.dao.DB_CloudActivity;
import com.kidsdynamic.data.dao.DB_Event;
import com.kidsdynamic.data.dao.DB_Todo;
import com.kidsdynamic.data.dao.DB_EventKids;
import com.kidsdynamic.data.dao.DB_RawActivity;
import com.kidsdynamic.data.dao.DB_FormatActivity;

import com.kidsdynamic.data.dao.UserDao;
import com.kidsdynamic.data.dao.KidsDao;
import com.kidsdynamic.data.dao.CloudActivityDao;
import com.kidsdynamic.data.dao.EventDao;
import com.kidsdynamic.data.dao.TodoDao;
import com.kidsdynamic.data.dao.EventKidsDao;
import com.kidsdynamic.data.dao.RawActivityDao;
import com.kidsdynamic.data.dao.FormatActivityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig kidsDaoConfig;
    private final DaoConfig cloudActivityDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig todoDaoConfig;
    private final DaoConfig eventKidsDaoConfig;
    private final DaoConfig rawActivityDaoConfig;
    private final DaoConfig formatActivityDaoConfig;

    private final UserDao userDao;
    private final KidsDao kidsDao;
    private final CloudActivityDao cloudActivityDao;
    private final EventDao eventDao;
    private final TodoDao todoDao;
    private final EventKidsDao eventKidsDao;
    private final RawActivityDao rawActivityDao;
    private final FormatActivityDao formatActivityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        kidsDaoConfig = daoConfigMap.get(KidsDao.class).clone();
        kidsDaoConfig.initIdentityScope(type);

        cloudActivityDaoConfig = daoConfigMap.get(CloudActivityDao.class).clone();
        cloudActivityDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        eventKidsDaoConfig = daoConfigMap.get(EventKidsDao.class).clone();
        eventKidsDaoConfig.initIdentityScope(type);

        rawActivityDaoConfig = daoConfigMap.get(RawActivityDao.class).clone();
        rawActivityDaoConfig.initIdentityScope(type);

        formatActivityDaoConfig = daoConfigMap.get(FormatActivityDao.class).clone();
        formatActivityDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        kidsDao = new KidsDao(kidsDaoConfig, this);
        cloudActivityDao = new CloudActivityDao(cloudActivityDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        todoDao = new TodoDao(todoDaoConfig, this);
        eventKidsDao = new EventKidsDao(eventKidsDaoConfig, this);
        rawActivityDao = new RawActivityDao(rawActivityDaoConfig, this);
        formatActivityDao = new FormatActivityDao(formatActivityDaoConfig, this);

        registerDao(DB_User.class, userDao);
        registerDao(DB_Kids.class, kidsDao);
        registerDao(DB_CloudActivity.class, cloudActivityDao);
        registerDao(DB_Event.class, eventDao);
        registerDao(DB_Todo.class, todoDao);
        registerDao(DB_EventKids.class, eventKidsDao);
        registerDao(DB_RawActivity.class, rawActivityDao);
        registerDao(DB_FormatActivity.class, formatActivityDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        kidsDaoConfig.getIdentityScope().clear();
        cloudActivityDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        todoDaoConfig.getIdentityScope().clear();
        eventKidsDaoConfig.getIdentityScope().clear();
        rawActivityDaoConfig.getIdentityScope().clear();
        formatActivityDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public KidsDao getKidsDao() {
        return kidsDao;
    }

    public CloudActivityDao getCloudActivityDao() {
        return cloudActivityDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

    public EventKidsDao getEventKidsDao() {
        return eventKidsDao;
    }

    public RawActivityDao getRawActivityDao() {
        return rawActivityDao;
    }

    public FormatActivityDao getFormatActivityDao() {
        return formatActivityDao;
    }

}
