package com.kidsdynamic.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "t_activity_format".
 */
public class DB_FormatActivity {

    private Long id;
    private Long actvId;
    private Long indoorId;
    private Long indoorSteps;
    private Long outdoorId;
    private Long outdoorSteps;
    private String macId;
    private String kidId;
    private Long distance;
    private Long time;

    public DB_FormatActivity() {
    }

    public DB_FormatActivity(Long id) {
        this.id = id;
    }

    public DB_FormatActivity(Long id, Long actvId, Long indoorId, Long indoorSteps, Long outdoorId, Long outdoorSteps, String macId, String kidId, Long distance, Long time) {
        this.id = id;
        this.actvId = actvId;
        this.indoorId = indoorId;
        this.indoorSteps = indoorSteps;
        this.outdoorId = outdoorId;
        this.outdoorSteps = outdoorSteps;
        this.macId = macId;
        this.kidId = kidId;
        this.distance = distance;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getActvId() {
        return actvId;
    }

    public void setActvId(Long actvId) {
        this.actvId = actvId;
    }

    public Long getIndoorId() {
        return indoorId;
    }

    public void setIndoorId(Long indoorId) {
        this.indoorId = indoorId;
    }

    public Long getIndoorSteps() {
        return indoorSteps;
    }

    public void setIndoorSteps(Long indoorSteps) {
        this.indoorSteps = indoorSteps;
    }

    public Long getOutdoorId() {
        return outdoorId;
    }

    public void setOutdoorId(Long outdoorId) {
        this.outdoorId = outdoorId;
    }

    public Long getOutdoorSteps() {
        return outdoorSteps;
    }

    public void setOutdoorSteps(Long outdoorSteps) {
        this.outdoorSteps = outdoorSteps;
    }

    public String getMacId() {
        return macId;
    }

    public void setMacId(String macId) {
        this.macId = macId;
    }

    public String getKidId() {
        return kidId;
    }

    public void setKidId(String kidId) {
        this.kidId = kidId;
    }

    public Long getDistance() {
        return distance;
    }

    public void setDistance(Long distance) {
        this.distance = distance;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
