package com.kidsdynamic.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "t_raw_activity".
 */
public class DB_RawActivity {

    private Long id;
    /** Not-null value. */
    private String indoorActivity;
    private String outdoorActivity;
    private Integer timeZoneOffset;
    private Long time;
    private String macId;
    private String status;

    public DB_RawActivity() {
    }

    public DB_RawActivity(Long id) {
        this.id = id;
    }

    public DB_RawActivity(Long id, String indoorActivity, String outdoorActivity, Integer timeZoneOffset, Long time, String macId, String status) {
        this.id = id;
        this.indoorActivity = indoorActivity;
        this.outdoorActivity = outdoorActivity;
        this.timeZoneOffset = timeZoneOffset;
        this.time = time;
        this.macId = macId;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getIndoorActivity() {
        return indoorActivity;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndoorActivity(String indoorActivity) {
        this.indoorActivity = indoorActivity;
    }

    public String getOutdoorActivity() {
        return outdoorActivity;
    }

    public void setOutdoorActivity(String outdoorActivity) {
        this.outdoorActivity = outdoorActivity;
    }

    public Integer getTimeZoneOffset() {
        return timeZoneOffset;
    }

    public void setTimeZoneOffset(Integer timeZoneOffset) {
        this.timeZoneOffset = timeZoneOffset;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getMacId() {
        return macId;
    }

    public void setMacId(String macId) {
        this.macId = macId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
