package com.kidsdynamic.data.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.kidsdynamic.data.dao.DB_EventKids;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "t_event_kids".
*/
public class EventKidsDao extends AbstractDao<DB_EventKids, Long> {

    public static final String TABLENAME = "t_event_kids";

    /**
     * Properties of entity DB_EventKids.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property KidsId = new Property(1, Long.class, "kidsId", false, "kids_id");
        public final static Property Name = new Property(2, String.class, "name", false, "name");
        public final static Property MacId = new Property(3, String.class, "macId", false, "macId");
        public final static Property FirmwareVersion = new Property(4, String.class, "firmwareVersion", false, "firmwareVersion");
        public final static Property Profile = new Property(5, String.class, "profile", false, "profile");
        public final static Property DateCreated = new Property(6, Long.class, "dateCreated", false, "date_created");
        public final static Property LastUpdate = new Property(7, Long.class, "lastUpdate", false, "last_update");
        public final static Property EventId = new Property(8, Long.class, "eventId", false, "event_id");
    };

    private DaoSession daoSession;

    private Query<DB_EventKids> dB_Event_EventKidsQuery;

    public EventKidsDao(DaoConfig config) {
        super(config);
    }
    
    public EventKidsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_event_kids\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"kids_id\" INTEGER," + // 1: kidsId
                "\"name\" TEXT," + // 2: name
                "\"macId\" TEXT," + // 3: macId
                "\"firmwareVersion\" TEXT," + // 4: firmwareVersion
                "\"profile\" TEXT," + // 5: profile
                "\"date_created\" INTEGER," + // 6: dateCreated
                "\"last_update\" INTEGER," + // 7: lastUpdate
                "\"event_id\" INTEGER);"); // 8: eventId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_event_kids\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DB_EventKids entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long kidsId = entity.getKidsId();
        if (kidsId != null) {
            stmt.bindLong(2, kidsId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String macId = entity.getMacId();
        if (macId != null) {
            stmt.bindString(4, macId);
        }
 
        String firmwareVersion = entity.getFirmwareVersion();
        if (firmwareVersion != null) {
            stmt.bindString(5, firmwareVersion);
        }
 
        String profile = entity.getProfile();
        if (profile != null) {
            stmt.bindString(6, profile);
        }
 
        Long dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(7, dateCreated);
        }
 
        Long lastUpdate = entity.getLastUpdate();
        if (lastUpdate != null) {
            stmt.bindLong(8, lastUpdate);
        }
 
        Long eventId = entity.getEventId();
        if (eventId != null) {
            stmt.bindLong(9, eventId);
        }
    }

    @Override
    protected void attachEntity(DB_EventKids entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DB_EventKids readEntity(Cursor cursor, int offset) {
        DB_EventKids entity = new DB_EventKids( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // kidsId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // macId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // firmwareVersion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // profile
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // dateCreated
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // lastUpdate
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // eventId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DB_EventKids entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKidsId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMacId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFirmwareVersion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setProfile(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDateCreated(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setLastUpdate(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setEventId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DB_EventKids entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DB_EventKids entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "eventKids" to-many relationship of DB_Event. */
    public List<DB_EventKids> _queryDB_Event_EventKids(Long eventId) {
        synchronized (this) {
            if (dB_Event_EventKidsQuery == null) {
                QueryBuilder<DB_EventKids> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EventId.eq(null));
                dB_Event_EventKidsQuery = queryBuilder.build();
            }
        }
        Query<DB_EventKids> query = dB_Event_EventKidsQuery.forCurrentThread();
        query.setParameter(0, eventId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEventDao().getAllColumns());
            builder.append(" FROM t_event_kids T");
            builder.append(" LEFT JOIN t_event T0 ON T.\"event_id\"=T0.\"event_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DB_EventKids loadCurrentDeep(Cursor cursor, boolean lock) {
        DB_EventKids entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DB_Event dB_Event = loadCurrentOther(daoSession.getEventDao(), cursor, offset);
        entity.setDB_Event(dB_Event);

        return entity;    
    }

    public DB_EventKids loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DB_EventKids> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DB_EventKids> list = new ArrayList<DB_EventKids>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DB_EventKids> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DB_EventKids> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
